# Project information
site_name: 'Ansible-NAS'
site_description: 'Build a fully functional NAS with an Ubuntu box and this playbook'



# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

